# Generated by Django 4.2.20 on 2025-05-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=20, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField(default=0.0)),
                ('intr_rate2', models.FloatField(default=0.0)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('save_trm', models.CharField(blank=True, max_length=10, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('dcls_strt_day', models.CharField(blank=True, max_length=20, null=True)),
                ('fin_co_subm_day', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=20, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField(default=0.0)),
                ('intr_rate2', models.FloatField(default=0.0)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('save_trm', models.CharField(blank=True, max_length=10, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('dcls_strt_day', models.CharField(blank=True, max_length=20, null=True)),
                ('fin_co_subm_day', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
