# Generated by Django 4.2.20 on 2025-05-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OHLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('interval', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
            ],
            options={
                'unique_together': {('code', 'interval', 'timestamp')},
            },
        ),
    ]
